name: Deploy to Render

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: |
      github.event_name == 'push' || 
      (github.event.pull_request.merged == true)

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
